### ISSUE TITLE
How to build app

### ISSUE THREAD

**Issue by pdp2015** [ArtCC/moto-alarm-project_linkit-one#1]
Hi, could you supply instructions on how to build the app for ios?

MAny Thanks

**Comment by ArtCC** [comment]
Hi!

Is not the one you have available in the App Store for free?

https://itunes.apple.com/us/app/moto-alarm-project/id1313229312?l=es&ls=1&mt=8

Regards! Arturo

**Comment by pdp2015** [comment]
It is yes available but i wanted ot see how its put together as an ios app and thought u had included the files here? unless im mistaken?

**Comment by ArtCC** [comment]
Ok, I'm thinking about publishing all the code of the iOS app too, but it will take a while.

Thank you very much! :)
